"use client";

import { useEffect, useState } from 'react';
import type { FormEvent } from 'react';
import { Lightbulb, ArrowUpRight, CheckCircle2, Sparkles } from 'lucide-react';
import { getDecisionInsights, makeTravelDecision } from '@/actions/decisions';
import { useGlobalFilters } from '@/lib/FilterContext';
import { usePreferences } from '@/components/AppPreferences';
import GlobalFilters from '@/components/GlobalFilters';

export default function DecisionsPage() {
  const { filters } = useGlobalFilters();
  const { language, theme } = usePreferences();
  const [insights, setInsights] = useState<any[]>([]);
  const [input, setInput] = useState({ budget: 1000, nationality: 'Myanmar', days: 5, travelers: 1, purpose: 'leisure' as const, preferredRegion: 'any' as const });
  const [recommendation, setRecommendation] = useState<any>(null);
  useEffect(() => { getDecisionInsights(filters).then(setInsights).catch(console.error); }, [filters]);
  const text = language === 'my';
  const isLight = theme === 'light';
  const decide = async (event: FormEvent) => { event.preventDefault(); setRecommendation(await makeTravelDecision(input)); };
  return <div className="flex flex-col gap-6 animate-in fade-in duration-500">
    <div><h1 className="text-3xl font-extrabold tracking-tight text-white">{text ? 'ဆုံးဖြတ်ချက် စင်တာ' : 'Decision Center'}</h1><p className="text-slate-400 mt-2">{text ? 'ဒေတာမှ လုပ်ဆောင်နိုင်သော အကြံပြုချက်များကို ရယူပါ။' : 'Turn tourism data into practical planning actions.'}</p></div>
    <GlobalFilters showYear />
    <section className="glass-panel p-6">
      <div className="flex items-start gap-3 mb-5"><div className={`w-10 h-10 rounded-xl flex items-center justify-center border ${isLight ? 'bg-purple-100 border-purple-200 text-purple-700' : 'bg-purple-900/40 text-purple-400 border-purple-800/30'}`}><Sparkles className="w-5 h-5" /></div><div><h2 className="text-xl font-bold text-slate-100">{text ? 'ခရီးစဉ် ဆုံးဖြတ်ချက် ဖန်တီးရန်' : 'Interactive trip decision'}</h2><p className="text-sm text-slate-400">{text ? 'သင့်အချက်အလက်များ ထည့်ပြီး အကြံပြုချက် ရယူပါ။' : 'Enter constraints and the system will recommend a destination, spend plan, and visa next step.'}</p></div></div>
      <form onSubmit={decide} className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-6 gap-4 items-end">
        <label className="text-sm font-semibold text-slate-400">Budget / person ($)<input type="number" min="0" value={input.budget} onChange={e => setInput({ ...input, budget: Number(e.target.value) })} className="mt-1.5 w-full rounded-lg border border-slate-700/50 bg-slate-950/50 px-3 py-2 text-slate-200 outline-none focus:border-cyan-500 transition-colors" /></label>
        <label className="text-sm font-semibold text-slate-400">Passport nationality<input value={input.nationality} onChange={e => setInput({ ...input, nationality: e.target.value })} placeholder="e.g. Thailand" className="mt-1.5 w-full rounded-lg border border-slate-700/50 bg-slate-950/50 px-3 py-2 text-slate-200 outline-none focus:border-cyan-500 transition-colors" /></label>
        <label className="text-sm font-semibold text-slate-400">Days<input type="number" min="1" max="60" value={input.days} onChange={e => setInput({ ...input, days: Number(e.target.value) })} className="mt-1.5 w-full rounded-lg border border-slate-700/50 bg-slate-950/50 px-3 py-2 text-slate-200 outline-none focus:border-cyan-500 transition-colors" /></label>
        <label className="text-sm font-semibold text-slate-400">Travellers<input type="number" min="1" max="20" value={input.travelers} onChange={e => setInput({ ...input, travelers: Number(e.target.value) })} className="mt-1.5 w-full rounded-lg border border-slate-700/50 bg-slate-950/50 px-3 py-2 text-slate-200 outline-none focus:border-cyan-500 transition-colors" /></label>
        <label className="text-sm font-semibold text-slate-400">Purpose<select value={input.purpose} onChange={e => setInput({ ...input, purpose: e.target.value as any })} className="mt-1.5 w-full rounded-lg border border-slate-700/50 bg-slate-950/50 px-3 py-2 text-slate-200 outline-none focus:border-cyan-500 transition-colors"><option value="leisure">Leisure</option><option value="business">Business</option><option value="family">Family</option></select></label>
        <label className="text-sm font-semibold text-slate-400">Region<select value={input.preferredRegion} onChange={e => setInput({ ...input, preferredRegion: e.target.value as any })} className="mt-1.5 w-full rounded-lg border border-slate-700/50 bg-slate-950/50 px-3 py-2 text-slate-200 outline-none focus:border-cyan-500 transition-colors"><option value="any">Best fit</option><option value="yangon">Yangon</option><option value="mandalay">Mandalay</option><option value="bagan">Bagan</option><option value="inle">Inle Lake</option><option value="shan">Shan State</option><option value="mon">Mon State</option><option value="rakhine">Rakhine State</option><option value="chin">Chin State</option><option value="kayin">Kayin State</option><option value="kachin">Kachin State</option><option value="sagaing">Sagaing Region</option><option value="tanintharyi">Tanintharyi Region</option><option value="ayeyarwady">Ayeyarwady Region</option><option value="naypyidaw">Naypyidaw</option><option value="beach">Beach / Ngapali</option></select></label>
        <button className="xl:col-span-6 md:col-span-2 rounded-lg bg-gradient-to-r from-cyan-600 via-blue-600 to-purple-600 px-4 py-3 text-sm font-bold text-white shadow-lg shadow-cyan-500/20 hover:from-cyan-500 hover:via-blue-500 hover:to-purple-500 hover:shadow-cyan-500/30 transition-all active:scale-[0.99]">{text ? 'ဆုံးဖြတ်ချက် ရယူရန်' : 'Generate recommendation'}</button>
      </form>
      {recommendation && <div className={`mt-6 rounded-xl border p-5 shadow-inner ${isLight ? 'border-cyan-200 bg-cyan-50' : 'border-cyan-800/50 bg-cyan-950/30'}`}><div className="flex flex-wrap items-center justify-between gap-3"><div><p className={`text-xs font-bold uppercase tracking-widest ${isLight ? 'text-cyan-700' : 'text-cyan-400'}`}>Recommendation · {recommendation.confidence}% confidence</p><h3 className="text-2xl font-extrabold text-white mt-1">{text ? recommendation.decisionMm : recommendation.decision}</h3></div><span className={`rounded-full px-3 py-1 text-xs font-bold uppercase border ${recommendation.risk === 'low' ? (isLight ? 'bg-emerald-100 border-emerald-200 text-emerald-700' : 'bg-emerald-900/40 border-emerald-800/50 text-emerald-400') : recommendation.risk === 'medium' ? (isLight ? 'bg-amber-100 border-amber-200 text-amber-700' : 'bg-amber-900/40 border-amber-800/50 text-amber-400') : (isLight ? 'bg-rose-100 border-rose-200 text-rose-700' : 'bg-rose-900/40 border-rose-800/50 text-rose-400')}`}>{recommendation.risk} budget risk</span></div><div className="grid grid-cols-2 md:grid-cols-4 gap-3 mt-5 text-sm"><div><span className="text-slate-400">Planned spend</span><strong className="block text-slate-200">${recommendation.estimatedSpend.toLocaleString()}</strong></div><div><span className="text-slate-400">Reserve</span><strong className="block text-slate-200">${recommendation.reserve.toLocaleString()}</strong></div><div><span className="text-slate-400">Daily / person</span><strong className="block text-slate-200">${recommendation.dailyPerPerson} / ${recommendation.benchmarkDailyCost} typical</strong></div><div><span className="text-slate-400">Safety score</span><strong className="block text-slate-200">{recommendation.safetyScore}/100</strong></div></div><div className="mt-5 grid grid-cols-1 md:grid-cols-2 gap-4 text-sm bg-slate-950/50 p-4 rounded-lg"><p className="text-slate-300"><strong className="text-slate-200">Visa:</strong> {recommendation.visaNote}</p><p className="text-slate-300"><strong className="text-slate-200">Seasonality:</strong> Peak {recommendation.peakMonths.join(', ') || 'varies'}.</p></div><div className="mt-4 text-sm text-slate-300"><strong className="text-slate-200">Safety:</strong> {recommendation.safetyNotes}</div><ul className="mt-3 list-disc pl-5 text-sm text-slate-400 space-y-1">{recommendation.reasons.map((reason: string) => <li key={reason} className="leading-relaxed">{reason}</li>)}</ul></div>}
    </section>
    <div className="grid grid-cols-1 lg:grid-cols-3 gap-5">
      {insights.map((insight) => <article key={insight.title} className="glass-card p-6 relative overflow-hidden transition-colors hover:bg-slate-900/60">
        <div className="flex items-start justify-between mb-5"><div className={`w-11 h-11 rounded-xl flex items-center justify-center border ${isLight ? 'bg-cyan-100 text-cyan-700 border-cyan-200' : 'bg-cyan-900/40 text-cyan-400 border-cyan-800/50'}`}><Lightbulb className="w-5 h-5" /></div><span className={`text-xs font-bold uppercase tracking-widest ${insight.priority === 'high' ? (isLight ? 'text-rose-600' : 'text-rose-400') : insight.priority === 'medium' ? (isLight ? 'text-amber-600' : 'text-amber-400') : (isLight ? 'text-emerald-600' : 'text-emerald-400')}`}>{insight.priority}</span></div>
        <h2 className="text-lg font-bold text-slate-100">{text ? insight.titleMm : insight.title}</h2><p className="text-sm text-slate-400 mt-2 min-h-12 leading-relaxed">{insight.detail}</p>
        <div className="mt-5 border-t border-slate-700/50 pt-4 flex gap-2 text-sm font-medium text-slate-300"><ArrowUpRight className={`w-4 h-4 shrink-0 mt-0.5 ${isLight ? 'text-cyan-600' : 'text-cyan-500'}`} />{insight.action}</div>
      </article>)}
    </div>
    <div className="glass-panel p-5 flex items-start gap-3 text-sm text-slate-400"><CheckCircle2 className={`w-5 h-5 shrink-0 ${isLight ? 'text-emerald-600' : 'text-emerald-500'}`} />{text ? 'အကြံပြုချက်များသည် ၂၀၂၅ ခန့်မှန်းဒေတာ ပါဝင်သောကြောင့် စီမံကိန်းအတွက် အသုံးပြုပါ။' : 'Planning note: 2025 figures are modelled estimates and should be replaced with official releases before external reporting.'}</div>
  </div>;
}
